name: Daily Commit

on:
  schedule:
    - cron: '0 15 * * *'   # 한국 시간 자정
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config --global user.name "auto-commit-bot"
          git config --global user.email "bot@example.com"

      - name: Make a daily commit
        run: |
          echo "Last commit at $(date) - $RANDOM" > log.txt
          git add log.txt
          git commit -m "Daily commit: $(date)" || echo "Nothing to commit"

      - name: Push changes
        env:
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push origin main
