name: Daily Multi-Commit

on:
  schedule:
    - cron: '0 15 * * *'  # KST 00:00 = UTC 15:00
  workflow_dispatch:

permissions:
  contents: write

jobs:
  multi_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config --global user.name "${{ secrets.GIT_NAME }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"

      - name: Make 20 commits
        run: |
          for i in {1..20}
          do
            if [ $i -eq 1 ]; then
              echo "Commit #$i at $(date)" > log.txt
            else
              echo "Commit #$i at $(date)" >> log.txt
            fi

            git add log.txt
            git commit -m "Daily commit ($i/20): $(date)"
            sleep 1
          done

      - name: Push changes
        env:
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push origin main
